package com.homer.vlcplugin.View;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.event.ChangeListener;
import uk.co.caprica.vlcj.binding.LibVlcConst;



public class NavigationView extends javax.swing.JPanel {
    
    // Defines the range of values and thus the granularity of the media position slider
    public static final int MIN_POSITION = 0;
    public static final int MAX_POSITION = 100000;
    
    
    
    public NavigationView() {
        
        initComponents();
        
        m_volumeSlider.setMinimum(LibVlcConst.MIN_VOLUME);
        m_volumeSlider.setMaximum(LibVlcConst.MAX_VOLUME);
        
        m_mediaPositionSlider.setMinimum(MIN_POSITION);
        m_mediaPositionSlider.setMaximum(MAX_POSITION);
    }
    
    
    
    // Labels
    public void setMediaPosition(String position) { m_mediaPositionLabel.setText(position); }
    public void setMediaDuration(String duration) { m_mediaDurationLabel.setText(duration); }
    
    // Sliders
    public void addVolumeSliderCallback(ChangeListener listener) { m_volumeSlider.addChangeListener(listener); }
    public void addMediaPositionSliderCallback(ChangeListener listener) { m_mediaPositionSlider.addChangeListener(listener); }
    public void setMediaPositionSlider(int value) { m_mediaPositionSlider.setValue(value); }
    public void setVolumeSlider(int value) { m_volumeSlider.setValue(value); }
    
    // Buttons
    public void addPlayButtonCallback(ActionListener listener) { m_playButton.addActionListener(listener); }
    public void addStopButtonCallback(ActionListener listener) { m_stopButton.addActionListener(listener); }
    public void addLoadButtonCallback(ActionListener listener) { m_loadButton.addActionListener(listener); }
    public void addVolumeButtonCallback(ItemListener listener) { m_volumeButton.addItemListener(listener); }
    
    public void setPlayButtonText(String text) { m_playButton.setText(text); }
    public void setVolumeButtonText(String text) { m_volumeButton.setText(text); }
    public void setVolumeButtonToggled(boolean isToggled) { m_volumeButton.setSelected(isToggled); }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_mediaPositionLabel = new javax.swing.JLabel();
        m_mediaPositionSlider = new javax.swing.JSlider();
        m_mediaDurationLabel = new javax.swing.JLabel();
        m_volumeSlider = new javax.swing.JSlider();
        m_playButton = new javax.swing.JButton();
        m_stopButton = new javax.swing.JButton();
        m_volumeButton = new javax.swing.JToggleButton();
        m_loadButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(m_mediaPositionLabel, org.openide.util.NbBundle.getMessage(NavigationView.class, "NavigationView.m_mediaPositionLabel.text")); // NOI18N

        m_mediaPositionSlider.setMaximum(100000);
        m_mediaPositionSlider.setValue(0);
        m_mediaPositionSlider.setMinimumSize(new java.awt.Dimension(0, 0));

        org.openide.awt.Mnemonics.setLocalizedText(m_mediaDurationLabel, org.openide.util.NbBundle.getMessage(NavigationView.class, "NavigationView.m_mediaDurationLabel.text")); // NOI18N

        m_volumeSlider.setMaximum(200);
        m_volumeSlider.setToolTipText(org.openide.util.NbBundle.getMessage(NavigationView.class, "NavigationView.m_volumeSlider.toolTipText")); // NOI18N
        m_volumeSlider.setValue(100);

        m_playButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(m_playButton, org.openide.util.NbBundle.getMessage(NavigationView.class, "NavigationView.m_playButton.text")); // NOI18N
        m_playButton.setActionCommand(org.openide.util.NbBundle.getMessage(NavigationView.class, "NavigationView.m_playButton.actionCommand")); // NOI18N

        m_stopButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(m_stopButton, org.openide.util.NbBundle.getMessage(NavigationView.class, "NavigationView.m_stopButton.text")); // NOI18N
        m_stopButton.setActionCommand(org.openide.util.NbBundle.getMessage(NavigationView.class, "NavigationView.m_stopButton.actionCommand")); // NOI18N

        m_volumeButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(m_volumeButton, org.openide.util.NbBundle.getMessage(NavigationView.class, "NavigationView.m_volumeButton.text")); // NOI18N
        m_volumeButton.setBorder(null);
        m_volumeButton.setBorderPainted(false);
        m_volumeButton.setContentAreaFilled(false);

        m_loadButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(m_loadButton, org.openide.util.NbBundle.getMessage(NavigationView.class, "NavigationView.m_loadButton.text")); // NOI18N
        m_loadButton.setActionCommand(org.openide.util.NbBundle.getMessage(NavigationView.class, "NavigationView.m_loadButton.actionCommand")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m_playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(m_volumeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_volumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m_mediaPositionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_mediaPositionSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_mediaDurationLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_mediaPositionLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(m_mediaDurationLabel))
                    .addComponent(m_mediaPositionSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(m_playButton)
                        .addComponent(m_stopButton)
                        .addComponent(m_loadButton))
                    .addComponent(m_volumeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(m_volumeSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton m_loadButton;
    private javax.swing.JLabel m_mediaDurationLabel;
    private javax.swing.JLabel m_mediaPositionLabel;
    private javax.swing.JSlider m_mediaPositionSlider;
    private javax.swing.JButton m_playButton;
    private javax.swing.JButton m_stopButton;
    private javax.swing.JToggleButton m_volumeButton;
    private javax.swing.JSlider m_volumeSlider;
    // End of variables declaration//GEN-END:variables
}
