package com.homer.vlcplugin.View;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.function.Consumer;



public class VideoView extends javax.swing.JPanel {

    // Callback to the function that draws a video frame
    private Consumer<Graphics2D> m_callback;
    
    
    
    public VideoView() {
        
        initComponents();
    }
    
    
    
    // Paint Callback
    public void setPaintCallback(Consumer<Graphics2D> callback) { m_callback = callback; }
    
    
    
    @Override
    protected void paintComponent(Graphics g) {
        
        super.paintComponent(g);
        
        if(m_callback != null)
            m_callback.accept((Graphics2D)g);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
